# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: gofunky/helmsman:test
    steps:
      - checkout
      - run:
          name: Build helmsman
          command: |
            echo "fetching dependencies ..."
            go get github.com/gofunky/helmsman/gcs
            go get github.com/gofunky/helmsman/aws
            echo "building ..."
            TAG=$(git describe --abbrev=0 --tags)-$(date +"%d%m%y")
            go build -ldflags '-X main.version='$TAG' -extldflags "-static"'
  
  test:
    docker:
    - image: gofunky/helmsman:test
    steps:
      - checkout 
      - run:
          name: Unit test helmsman  
          command: |
            echo "fetching dependencies ..."
            go get github.com/gofunky/helmsman/gcs
            go get github.com/gofunky/helmsman/aws
            echo "running tests ..."
            go test -v

                
workflows:
  version: 2
  build-test-push-release:
    jobs:
      - build
      - test:
          requires:
            - build       
      - release:
          requires:
            - test
          filters:
            branches:
              only: master 
            tags:
              only: /^v.*/       