[metadata]
org = "test.org"
description = "Test Chart"

[settings]
kubeContext = "minikube"
storageBackend = "secret"

[namespaces]
    [namespaces.test]
    installTiller = true
    protected = true
    tillerServiceAccount = "test-sa"

[apps]
    # nginx will be deployed using the Tiller in the test namespace
    [apps.test]
    namespace = "test"
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "test_files/example_chart" # changing the chart name means delete and recreate this release
    version = "0.1.0" # chart version
    ### Optional values below
    name = "test-nginx" # should be unique across all apps which are managed by the same Tiller
    valuesFile = "" # leaving it empty uses the default chart values
    purge = true # will only be considered when there is a delete operation
    test = true # run the tests when this release is installed for the first time only
    protected = true
    priority= -2
    wait = true
